### ISSUE TITLE
How to inject a custom relationship from existing entity in state

### ISSUE THREAD

**Issue by iroy2000** [andyhite/redux-jsonapi#10]
I'm trying to construct a request with "custom relationship", let's say the relationship is on frontend, and the backend server doesn't have that relationship.  How do I inject "custom" relationship before I send to apiActions.write ??

```
    let request = {
      _type: 'search',
      name: "filter name",
      criteria: {
        "type": [
          "snack"
        ]
      }
    }

    const data = await dispatch(apiActions.write(request));

```

And this is what I want  ( the data is fake, but how could I inject an arbitrary existing relationship from state )

```
{
  "data": {
    "type": "snack-filter",
    "attributes": {
      "name": "filter name",
       "criteria": {
        "type": [
          "snack"
        ]
      }
    },

    //  for example, the user is an exisitng entity in the state, but doesn't have direct relationship with filter
    "relationships": {
      "user": {
        "data": {
          "type": "parent",
          "id": "123"
        }
      }
    }
  }
}
```

**Comment by iroy2000** [comment]
I looked into the codebase, you can construct a relationship by using a `function` ( for example, user: function() ... ) in the payload.  I think I solved it in my own way, but since it is not documented,  what would be the best way to solve it ??

**Comment by andyhite** [comment]
I think you have it figured out – to add the extra relationship, just assign a function that returns the associated entity. The function will be called and the result will be serialized when it's written.

**Comment by iroy2000** [comment]
Thanks.
