### ISSUE TITLE
deserialize function "store" is undefined ??

### ISSUE THREAD

**Issue by iroy2000** [andyhite/redux-jsonapi#11]
I'm trying to debug the library and found out that if I call a "relationship function", it run the deserialize(), but it also complain that the "store" is undefined.   I'm trying to follow the configuration in the docs, anything could gone wrong?  Because "deserialize" is an internal function of this lib ...

![screen shot 2017-05-11 at 12 29 37 pm](https://cloud.githubusercontent.com/assets/487520/25968217/9065c328-3645-11e7-8e33-85e5ef515b4a.png)

![screen shot 2017-05-11 at 12 29 46 pm](https://cloud.githubusercontent.com/assets/487520/25968221/93d9fe3e-3645-11e7-9345-178486908d40.png)

**Comment by iroy2000** [comment]
Doesn't seem like the "fetchRelationships" is in the npm package, did you push the latest to npm ?

**Comment by andyhite** [comment]
I'm going to be cutting a new version of the lib today, so if this isn't in the most recent release it will be soon.
