### ISSUE TITLE
custom fetch implementation 

### ISSUE THREAD

**Issue by cfey** [andyhite/redux-jsonapi#5]
It would be great if we allow people to use their own fetch implementation.
We can add it as argument in the createMiddleware method

**Comment by andyhite** [comment]
I was thinking about this just now, and realized that you should be able to specify a fetch implementation without any change to `redux-jsonapi`. I haven't tested it, but setting `window.fetch` (or `global.fetch` if you're in a node execution context) to the implementation you want to use should take care of this. At the entry-point of your application, try putting the following (make sure it's before any other code, especially where you import the `redux-jsonapi` middleware:

``` js
import eFetch from 'f-etag';
window.fetch = eFetch;
```

This library is technically not dependent on any specific implementation of fetch, as long as it's defined globally (on `global` or `window`, depending on context) and has an interface that looks like `fetch`.

**Comment by cfey** [comment]
agree
